### ISSUE TITLE
Is the socket.io only used for front-end connected with back-end?

### ISSUE THREAD

**Issue by donge** [nlaplante/syslogng-web#25]
If I am not wrong, it's not used for reload the logs in mongodb.
Why don't you do that?

**Comment by nlaplante** [comment]
It's only used to connect to the nodejs backend, which in turn is connected to a MongoDB cursor. What do you mean by reloading the logs in MongoDB ?

**Comment by donge** [comment]
I mean if logs are added, is any listener there, to notice the change from
back-end to front-end via socket.io.

Thanks,
Dongdong
​

**Comment by nlaplante** [comment]
Yes that's the whole point of this app. The nodejs server opens a tailable cursor (it never closes and waits for data), and when data is received, it sends the data to the browser through web sockets.

**Comment by donge** [comment]
ok, got it, thanks, not sure why it's not work in my local laptop.

2015-04-22 21:39 GMT+08:00 Nicolas Laplante <notifications@github.com>:
