### ISSUE TITLE
Error: Cannot find module '/home/syslog-ng/app.js'

### ISSUE THREAD

**Issue by Maxwell101** [nlaplante/syslogng-web#26]
syslog-ng@syslogng-virtual-machine:~$ sudo node app.js 
module.js:340
    throw err;
          ^
Error: Cannot find module '/home/syslog-ng/app.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Any ideas how to fix this?

**Comment by nlaplante** [comment]
Is there any reason to run this as a super user?

**Comment by Maxwell101** [comment]
For write permissions.  It found the app.js but now it’s looking for the first file listed in the app.js file “./router”.  Looks like this:


ar EventEmitter     = require('events').EventEmitter,

    Router           = require('./router').Router,

    Window           = require('./window'),

    Menu             = require('./menu'),

    _App             = require('./bindings').App,

    NativeWindow     = require('./bindings').NativeWindow,

    NativeMenu       = require('./bindings').NativeMenu,

    NativeStatusIcon = require('./bindings').NativeStatusIcon,

    WindowSettings   = require('./settings').WindowSettings,

    AppSettings      = require('./settings').AppSettings;



var _init          = require('./bindings').init,

    decorate       = require('./utils').decorate,

    inherit        = require('./utils').inherit,

    isObject       = require('./utils').isObject,

    staticRouter   = require('./router').staticRouter,

    pathResolve    = require('path').resolve;

I’m guessing it won’t be able to find the others listed.  Not sure what I did wrong.

**Comment by nlaplante** [comment]
And if you run it without sudo, what's the result?

**Comment by Maxwell101** [comment]
syslog-ng@syslogng-virtual-machine:~/node_modules/appjs/lib$ node app.js 

/home/syslog-ng/node_modules/appjs/lib/bindings.js:9
  throw new Error("AppJS requires Node.js v0.8");
        ^
Error: AppJS requires Node.js v0.8
    at Object.<anonymous> (/home/syslog-ng/node_modules/appjs/lib/bindings.js:9:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/syslog-ng/node_modules/appjs/lib/window.js:4:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
syslog-ng@syslogng-virtual-machine:~/node_modules/appjs/lib$ 



It's looking for node v0.8.  I have 0.10.25




________________________________________

**Comment by nlaplante** [comment]
Here's what I get locally, on master branch:

```
$ node app.js 
Option log level is not valid. Please refer to the README.
initializing subsystem
An error occured while setting up syslogng-web: connect ECONNREFUSED
Bail out

nicolas at nemesis in ~/Projects/syslogng-web on master
$ node --version
v0.10.38

nicolas at nemesis in ~/Projects/syslogng-web on master
$ npm --version
1.4.28
```

I'd suggest doing an npm update, as I cannot reproduce the error.

Don't mind the error in my output, I didn't configure the mongodb server.

**Comment by Maxwell101** [comment]
I tried that.  Message says I already have the latest version.

**Comment by Maxwell101** [comment]
Time for me to go home.  I’ll get back to it tomorrow.  Thanks for the help.

**Comment by Maxwell101** [comment]
Is the attached file the right app.js to start syslog-ng web?

Thanks

**Comment by nlaplante** [comment]
I don't see any attachment. The app.js from master branch is the correct one.
