### ISSUE TITLE
Trying to cap the mongodb

### ISSUE THREAD

**Issue by Maxwell101** [nlaplante/syslogng-web#27]
I get this error message:

> db.runCommand({
... convertToCapped: 'messages',
... size: 100000
... });
{
	"ok" : 0,
	"errmsg" : "cloneCollectionAsCapped failed: { errmsg: \"exception: source collection syslog.messages does not exist\", code: 10301, ok: 0.0 }"
}
> ^C
bye

**Comment by nlaplante** [comment]
Try this:

http://docs.mongodb.org/manual/reference/method/db.createCollection/

**Comment by Maxwell101** [comment]
Thanks.  When I enter this in the shell:
db.createCollection("messages", { capped : true, size : 100000, } )

Where is the “messages” file stored?  When I run “nodejs app.js” I get this:


An error occured while setting up syslogng-web: collection syslog.messages not found

Bail out

**Comment by nlaplante** [comment]
syslog-ng should create it when configured to post log messages to mongodb.
