### ISSUE TITLE
No logs appearing in syslogng-web interface

### ISSUE THREAD

**Issue by Maxwell101** [nlaplante/syslogng-web#30]
I've got the syslog-ng service running and syslogng-web up but there's no logs appearing.  Syslog is collecting data in /var/lib/mongodb - file names are syslog.0 through syslog.6

**Comment by nlaplante** [comment]
Is there any data when accessing the database via the MongoDB client?

**Comment by Maxwell101** [comment]
Actually, I had to start over with Ubuntu Server 64 bit.  I was using Ubunto 32 bit before and when the data reached 2g Mongo quit.  Now it’s issues with the server version of Ubuntu – It’s not letting me install Apache2.


user@syslog:~$ sudo apt-get install apache2
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2 : Depends: apache2-bin (= 2.4.7-1ubuntu4.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


Can’t find anything online to fix this.

**Comment by Maxwell101** [comment]
In the process of installing syslog web again.  I'm at the point "bower install"  When I type that in I get no such file or directory.

________________________________

**Comment by Maxwell101** [comment]
I got everything up and running.  One question:  When installing the dependencies, confit = require('./config'),

pkg = require('./package'),

Threw error message “repository not found”  are these necessary to run properly?

**Comment by Maxwell101** [comment]
How do you access the database via the MongoDB client?

**Comment by nlaplante** [comment]
See this: http://docs.mongodb.org/manual/reference/mongo-shell/

**Comment by Maxwell101** [comment]
Thanks.  Have you seen this before?  I entered destination mongodb { mongodb(); };
log { source(src); destination(mongodb); }; into syslogng.conf as in the instuctions.  I know I'm missing something.

user@syslog:~/syslogng-web$ sudo service syslog-ng restart
 * Stopping system logging syslog-ng                                                                           [ OK ] 
 * Starting system logging syslog-ng                                                                                  Error parsing destination, destination plugin mongodb not found in /etc/syslog-ng/syslog-ng.conf at line 30, column 23:

destination mongodb { mongodb() ; };
                      ^^^^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng

________________________________________

**Comment by Maxwell101** [comment]
Hi, Can you tell what I'm doing wrong here?  I entered destination mongodb { mongodb(); };  
log { source(src); destination(mongodb); }; in syslogng.conf as in the directions and this is what happens:

user@syslog:~/syslogng-web$ sudo service syslog-ng restart
 * Stopping system logging syslog-ng                                                                           [ OK ] 
 * Starting system logging syslog-ng                                                                                  Error parsing destination, destination plugin mongodb not found in /etc/syslog-ng/syslog-ng.conf at line 30, column 23:

destination mongodb { mongodb() ; };
                 ^^^^^^^

**Comment by Maxwell101** [comment]
One more question and I’ll stop bugging you.  I noticed at the bottom of the syslogng-web interface there’s 40 placeholders and they only have the most recent data.  Is there a way to go back farther the those 40?

Thanks

**Comment by nlaplante** [comment]
If you look at https://github.com/nlaplante/syslogng-web/blob/master/public/javascripts/controllers.js#L72 you'll see there's a limit on the number of messages. This is because if you keep too much, the browser will eat up memory pretty fast. Feel free to increase this limit to suit your needs. Unfortunately there's no easy way to configure this except by editing the file directly.

**Comment by Maxwell101** [comment]
Good to know.


Thanks
Rick

**Comment by Maxwell101** [comment]
I changed the # to 5000 and still only 40 pages.
